"use client";

import { useLocale, useTranslations } from "next-intl";
import { useEffect, useState } from "react";
import { Medal, rarityColor } from "@/components/profile/parts";
import { MEDAL_KEY, type AchievementCode, isAchievementCode } from "@/lib/game/achievements";
import type { Rarity } from "@/lib/profile/public";
import type { ViewerSummary } from "@/lib/profile/viewer";
import { publicClient } from "@/lib/supabase/public";

type Earned = { code: AchievementCode; rarity: Rarity; seasonId: number | null };

/** The achievements a reign earned when it was taken (awarded in the same transaction). */
function useEarnedWith(reignId: number): Earned[] {
  const [earned, setEarned] = useState<Earned[]>([]);
  useEffect(() => {
    const db = publicClient();
    let cancelled = false;
    void db
      .from("profile_achievements")
      .select("achievement_code, achievements (rarity, season_id)")
      .eq("reign_id", reignId)
      .order("earned_at")
      .then(({ data }) => {
        if (cancelled || !data) return;
        setEarned(
          data.flatMap((row) =>
            isAchievementCode(row.achievement_code) && row.achievements
              ? [{ code: row.achievement_code, rarity: row.achievements.rarity, seasonId: row.achievements.season_id }]
              : [],
          ),
        );
      });
    return () => {
      cancelled = true;
    };
  }, [reignId]);
  return earned;
}

const SECONDARY =
  "hit-area m-1 flex h-11 grow items-center justify-center bg-crown-hall px-4 text-14 font-bold whitespace-nowrap shadow-relief-card hover:bg-crown-stone focus-visible:outline-offset-[6px] active:bg-crown-ink";

/**
 * The success screen's moment of sharing, for a signed-in buyer: the victory card their link
 * previews, ways to share it, and what this takeover unlocked.
 */
export function ReignShare({ reignId, viewer, size }: { reignId: number; viewer: ViewerSummary; size: "mobile" | "desktop" }) {
  const t = useTranslations("payment.share");
  const share = useTranslations("share");
  const achievement = useTranslations("achievement");
  const medals = useTranslations("medals");
  const locale = useLocale();
  const earned = useEarnedWith(reignId);
  const [copied, setCopied] = useState(false);

  const card = `/og/victory/${reignId}?locale=${locale}`;
  const story = `/og/victory/${reignId}?locale=${locale}&size=story`;
  // The profile link previews the current reign's victory card (the profile page's metadata).
  const profilePath = `/${locale}/u/${viewer.name.toLowerCase()}`;
  const copy = () => {
    void navigator.clipboard?.writeText(`${window.location.origin}${profilePath}`).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    });
  };
  const post = () => {
    const url = `${window.location.origin}${profilePath}`;
    window.open(`https://x.com/intent/post?text=${encodeURIComponent(share("vicHead"))}&url=${encodeURIComponent(url)}`, "_blank", "noopener");
  };

  return (
    <div className={`flex flex-col ${size === "mobile" ? "gap-3" : "gap-4"}`} data-testid="reign-share">
      <p className={`font-bold text-pretty ${size === "mobile" ? "text-16 leading-snug" : "text-20 leading-[1.35]"}`}>{t("title")}</p>
      {/* An exact fraction of the 1200×630 card, nearest-neighbor, so its pixel art stays sharp: a
          quarter on phones and narrow desktops, half where the success modal is wide enough. */}
      {/* eslint-disable-next-line @next/next/no-img-element -- generated by /og, not a static asset */}
      <img
        src={card}
        width={1200}
        height={630}
        alt={t("cardAlt", { name: viewer.name })}
        className={`block aspect-[1200/630] h-auto w-[300px] max-w-none flex-none bg-crown-velvet [image-rendering:pixelated] ${size === "desktop" ? "xl:w-[600px]" : ""}`}
      />
      <div className="-m-1 flex flex-wrap">
        <button type="button" onClick={copy} className={SECONDARY}>
          <span aria-live="polite">{copied ? achievement("copied") : t("copy")}</span>
        </button>
        <button type="button" onClick={post} className={SECONDARY}>
          {t("postX")}
        </button>
        <a href={story} download={`take-the-crown-${reignId}-story.png`} className={SECONDARY}>
          {t("story")}
        </a>
      </div>
      {earned.length > 0 && (
        <div className="flex flex-col gap-2.5 pt-1">
          <div className="text-14 font-bold">{t("unlocked")}</div>
          <ul className="flex flex-col gap-2">
            {earned.map((e) => (
              <li key={e.code} className="flex items-center gap-3 bg-crown-velvet p-2 pr-3">
                <Medal code={e.code} on scale={2} />
                <div className="flex min-w-0 flex-col gap-0.5">
                  <span className="text-14 font-bold">{medals(`${MEDAL_KEY[e.code]}.name`)}</span>
                  <span className="text-12 font-medium" style={{ color: rarityColor(e.rarity, e.seasonId) }}>
                    {achievement(`rar.${e.rarity === "seasonal" ? "seasonal" : e.rarity}`)}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
